# Generated by Django 2.2.16 on 2020-11-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveIntegerField(verbose_name='Следующее действие')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='ModelGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=None, max_length=128)),
                ('beginned_game', models.BooleanField(default=False)),
                ('turn', models.PositiveIntegerField(default=None, verbose_name='Ход')),
            ],
        ),
        migrations.CreateModel(
            name='StartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witcher_level', models.PositiveIntegerField(verbose_name='Уровень Ведьмака')),
                ('enemy_level', models.PositiveIntegerField(verbose_name='Уровень Противников')),
                ('enemy_amount', models.PositiveIntegerField(verbose_name='Количество противников')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='WitcherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень Ведьмака')),
                ('hp', models.IntegerField(verbose_name='Здоровье Ведьмака')),
                ('attack_power', models.IntegerField(verbose_name='Сила атаки')),
                ('crit', models.FloatField(default=0.16, verbose_name='Шанс крита')),
                ('last_turn_power_attack', models.IntegerField(default=-1, verbose_name='Последнее использование силовой атаки')),
                ('max_hp', models.IntegerField(verbose_name='Максимальное здоровье')),
                ('threshold_hp', models.FloatField(verbose_name='Пороговое здоровье')),
                ('energy', models.IntegerField(default=100, verbose_name='Энергия')),
                ('max_energy', models.IntegerField(default=100, verbose_name='Максимальная энергия')),
                ('shield', models.IntegerField(default=0, verbose_name='Щит')),
                ('accuracy', models.FloatField(default=0.95, verbose_name='Точность')),
                ('in_use', models.BooleanField(default=False)),
                ('swallow', models.IntegerField(default=2, verbose_name='Ласточка')),
                ('thunder', models.IntegerField(default=2, verbose_name='Гром')),
                ('tawny_owl', models.IntegerField(default=1, verbose_name='Неясыть')),
                ('last_swallow', models.IntegerField(default=-1, verbose_name='Последнее использование Ласточки')),
                ('last_thunder', models.IntegerField(default=-1, verbose_name='Последнее использование Грома')),
                ('last_tawny_owl', models.IntegerField(default=-1, verbose_name='Последнее использование Неясыти')),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='witchersite.ModelGame')),
            ],
        ),
        migrations.CreateModel(
            name='GhostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень противника')),
                ('hp', models.IntegerField(default=0, verbose_name='Здоровье противника')),
                ('attack_power', models.PositiveIntegerField(default=0, verbose_name='Сила атаки')),
                ('accuracy', models.FloatField(default=0, verbose_name='Точность')),
                ('ability', models.IntegerField(default=3, verbose_name='Способности')),
                ('crit', models.FloatField(default=0, verbose_name='Крит')),
                ('treshold_hp', models.IntegerField(default=0, verbose_name='Пороговое здоровье')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('last_turn_ability_used', models.IntegerField(default=-1, verbose_name='Ход использования способности')),
                ('in_astral', models.BooleanField(default=False, verbose_name='состояние ухода в астрал')),
                ('in_use', models.BooleanField(default=False)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='witchersite.ModelGame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrownerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень противника')),
                ('hp', models.IntegerField(default=0, verbose_name='Здоровье противника')),
                ('attack_power', models.PositiveIntegerField(default=0, verbose_name='Сила атаки')),
                ('accuracy', models.FloatField(default=0, verbose_name='Точность')),
                ('ability', models.IntegerField(default=3, verbose_name='Способности')),
                ('crit', models.FloatField(default=0, verbose_name='Крит')),
                ('treshold_hp', models.IntegerField(default=0, verbose_name='Пороговое здоровье')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('in_rage', models.BooleanField(default=False, verbose_name='В ярости')),
                ('attack_speed', models.IntegerField(default=1, verbose_name='Скорость атаки')),
                ('in_use', models.BooleanField(default=False)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='witchersite.ModelGame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BanditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень противника')),
                ('hp', models.IntegerField(default=0, verbose_name='Здоровье противника')),
                ('attack_power', models.PositiveIntegerField(default=0, verbose_name='Сила атаки')),
                ('accuracy', models.FloatField(default=0, verbose_name='Точность')),
                ('ability', models.IntegerField(default=3, verbose_name='Способности')),
                ('crit', models.FloatField(default=0, verbose_name='Крит')),
                ('treshold_hp', models.IntegerField(default=0, verbose_name='Пороговое здоровье')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('attack_speed', models.IntegerField(default=1, verbose_name='Скорость атаки')),
                ('dodge', models.BooleanField(default=False, verbose_name='Уклонение')),
                ('special_ability', models.IntegerField(default=1, verbose_name='Спец. способность')),
                ('cry_chance', models.FloatField(default=0.85, verbose_name='Шанс клича')),
                ('crying', models.BooleanField(default=False, verbose_name='Клич')),
                ('block', models.BooleanField(default=False, verbose_name='Шанс блока')),
                ('in_use', models.BooleanField(default=False)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='witchersite.ModelGame')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
