# Generated by Django 2.2.16 on 2020-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witchersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelgame',
            name='turn',
            field=models.PositiveIntegerField(default=0, verbose_name='Ход'),
        ),
    ]
