# Generated by Django 2.2.16 on 2020-11-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witchersite', '0002_auto_20201114_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banditmodel',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='drownermodel',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='ghostmodel',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='witchermodel',
            name='in_use',
        ),
    ]
